### ISSUE TITLE
Tab Titles

### ISSUE THREAD

**Issue by mapsonx** [vovcacik/cut-copy-paste-tabs#1]
Is there any chance that the tab titles could remain the original names instead of changing to the url

**Comment by vovcacik** [comment]
Hi, not really. Why you need something like that?

**Comment by mapsonx** [comment]
I want to copy and paste the tab exactly as it is.  Most of my tabs have identifiable names.  With multiple tabs, it makes it a lot easier to identify an individual tab if it has a name instead of a url, especially when you can only see a small fraction of the url depending on the width of the tab

**Comment by vovcacik** [comment]
Ah I see, when you paste multiple URLs, the newly created tabs have URLs on labels instead of the page title. This happens because pasting URLs create tabs that are not immediately loaded, hence the page title is unknown at the time and URLs are displayed.

This handles the Firefox itself not this addon. I could load the tabs, but there are good reasons not to:
- pasting lots of URLs could lead to crash
- RAM usage
- responsivness during pasting

Thanks for your understanding.
